export const phrases = [
  ['Z', 'Eating during meeting'],
  ['Z', '“Sorry, can you repeat that?”'],
  ['Z', 'Joked about the long commute'],
  ['Z', '“Can we take this offline?”'],
  ['Z', 'Wearing pajamas'],
  ['Z', '“Hi, who just joined?”'],
  ['Z', 'Funny camera angle'],
  ['Z', 'Forgot camera was on/did something embarrassing'],

  ['I', '(Loud painful echo/feedback)'],
  ['I', '“Sorry, I was on mute”'],
  ['I', 'Thought they were on mute, said something embarrassing '],
  ['I', '“My connection is bad”'],
  ['I', 'Kid noises in background'],
  ['I', 'Texting during the meeting'],
  ['I', '(For over-talkers) “Sorry, go ahead”'],
  ['I', 'Pager goes off during meeting'],

  ['N', '“Hi! Can you hear me?”'],
  ['N', 'Someone mentions COVID'],
  ['N', 'Awkward Silence'],
  ['N', 'Takes multiple tries to join'],
  ['N', 'First one to join the meeting'],
  ['N', 'Someone accidentally leaves meeting'],
  ['N', 'Distracted by messy background'],
  ['N', '“Next slide please”'],

  ['G', 'Video Freezes'],
  ['G', 'Not wearing pants'],
  ['G', 'On video wearing mask'],
  ['G', 'Terrible echo'],
  ['G', 'Sirens blaring in background'],
  ['G', '“Sorry I have to hop on another call”'],
  ['G', 'Joins late wants a recap'],
  ['G', '“Stay safe”'],
  ['G', '“Sorry, you cut out”'],

  ['O', 'Sends private message to all'],
  ['O', '“Quiet group today”'],
  ['O', 'Bed Head'],
  ['O', '“I think there is a lag”'],
  ['O', 'Someone can’t figure out how to mute/unmute'],
  ['O', '“Can you see my screen?”'],
  ['O', 'Disappears into virtual background'],
  ['O', '“Can everyone please mute themselves?”'],
  ['O', 'Sound of someone typing '],
  ['O', 'Screen-shares the wrong screen'],
];
